export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RESET_AUTHED = 'RESET_AUTHED';

// routes
export const CHANGE_PATH = 'CHANGE_PATH';

// accessToken
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';

// songs
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';

// likes
export const RECEIVE_LIKES = 'RECEIVE_LIKES';

// playlists
export const RECEIVE_AUTHED_PLAYLISTS = 'RECEIVE_AUTHED_PLAYLISTS';

// followings
export const RECEIVE_AUTHED_FOLLOWINGS = 'RECEIVE_AUTHED_FOLLOWINGS';

// player
export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_SELECTED_PLAYLISTS = 'CHANGE_SELECTED_PLAYLISTS';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';
